#!/usr/bin/env python
"""Formal-harness builder for the Prover (build step B).

Generates an sby-ready formal harness skeleton from a module's port list. The MECHANICAL parts
are automated; the parts that need whole-module COMPREHENSION are scaffolded with TODO markers:

  AUTOMATED (mechanical, but load-bearing):
    - drive EVERY input (an unconnected input becomes a free var -> UNSOUND proof)
    - detect clock ports (*clk*) -> single formal clock 'clk' (collapse; multiclock noted)
    - detect reset ports (*rst*/*reset*) -> generated rst_n
    - instantiate the DUT with ALL ports, outputs of interest (*active/*valid/*done/*rdy) wired out
  SCAFFOLDED (you MUST fill in — comprehension required, see ../experiments/formal-demo/README.md):
    - the ENABLING PROTOCOL: config/enable/mode inputs flagged. e.g. ext_backTelInterface only
      arms after a pcmReg_wr_en config-write latches the mode regs; a fragment harness that just
      pokes the unit's pin FAILS (both fixed & buggy). Drive the real enabling sequence here.
    - the INTENT PROPERTY: pick a template from property-library.md (T4/T5/T6/FSM-safety).

Usage:
  python harness_builder.py <module.v> [module_name]   # prints harness to stdout
"""
import re, sys, os

DIRS = ('input', 'output', 'inout')


def header_text(text, modname):
    m = re.search(r'\bmodule\s+(' + (modname or r'\w+') + r')\s*\(', text)
    if not m:
        raise SystemExit(f"module {'' if not modname else modname+' '}declaration not found")
    name = m.group(1)
    i = m.end()
    depth = 1
    while i < len(text) and depth:
        if text[i] == '(':
            depth += 1
        elif text[i] == ')':
            depth -= 1
        i += 1
    return name, text[m.end():i - 1]


def strip_comments(s):
    s = re.sub(r'/\*.*?\*/', '', s, flags=re.S)
    s = re.sub(r'//[^\n]*', '', s)
    return s


def parse_ports(hdr):
    hdr = strip_comments(hdr)
    ports = []
    for decl in hdr.split(','):
        decl = decl.strip()
        if not decl:
            continue
        m = re.match(r'(input|output|inout)\s+(?:reg\s+|wire\s+|logic\s+)?(\[[^\]]+\]\s*)?(\w+)', decl)
        if not m:
            # continuation: a bare name after a previous direction (comma-split multi-name decl)
            m2 = re.match(r'(\[[^\]]+\]\s*)?(\w+)$', decl)
            if m2 and ports:
                ports.append((ports[-1][0], (m2.group(1) or '').strip(), m2.group(2)))
            continue
        ports.append((m.group(1), (m.group(2) or '').strip(), m.group(3)))
    return ports


def width_zero(width):
    if not width:
        return "1'b0"
    m = re.match(r'\[\s*(\w+)\s*:\s*(\w+)\s*\]', width)
    return f"{width.strip()} 0" if not m else f"{{{width.strip().count(':') and ''}}}".strip() or "'0"  # fallback


def zero_lit(width):
    if not width:
        return "1'b0"
    # try numeric width
    m = re.match(r'\[\s*(\d+)\s*:\s*(\d+)\s*\]', width)
    if m:
        n = abs(int(m.group(1)) - int(m.group(2))) + 1
        return f"{n}'d0"
    return "'0"  # parametric width


def classify(name):
    n = name.lower()
    if re.search(r'clk|clock', n):
        return 'clock'
    if re.search(r'rst|reset', n) and not re.search(r'restart', n):
        return 'reset'
    if re.search(r'_en\b|_wr_en|reg_wr|_mode\b|cfg|config|_load|exec|_pulse|enable', n):
        return 'enable'
    return 'data'


def out_of_interest(name):
    return bool(re.search(r'(active|valid|done|rdy|ready|busy|ack|err)\b', name.lower()))


def build(path, modname=None):
    text = open(path, encoding='utf-8', errors='replace').read()
    name, hdr = header_text(text, modname)
    ports = parse_ports(hdr)
    ins = [p for p in ports if p[0] == 'input']
    outs = [p for p in ports if p[0] in ('output', 'inout')]
    clocks = [p for p in ins if classify(p[2]) == 'clock']
    resets = [p for p in ins if classify(p[2]) == 'reset']
    enables = [p for p in ins if classify(p[2]) == 'enable']
    datas = [p for p in ins if classify(p[2]) == 'data']

    L = []
    A = L.append
    A('`default_nettype none')
    A(f'// Formal harness skeleton for {name} -- generated by harness_builder.py.')
    A('// AUTOMATED: every input driven, clocks collapsed to clk, all ports instantiated.')
    A('// >>> YOU MUST FILL the TODO sections (enabling protocol + intent property) <<<')
    A('// Lesson: a fragment harness that skips the enabling protocol FAILS (see formal-demo README).')
    A('')
    A('module ftb (input wire clk);')
    A('    reg [7:0] step = 8\'d0;')
    A('    always @(posedge clk) step <= step + 8\'d1;')
    A('    wire rst_n = (step >= 8\'d1);            // 1-cycle reset, then run')
    A('')
    if enables or datas:
        A('    // value(s)/cycle(s) under test (solver-chosen). Constrain the scenario below.')
        A('    (* anyconst *) reg [7:0] fire;          // e.g. the cycle a control pulse fires')
        A('')
    A('    // ---- outputs of interest (auto-wired) ----')
    woi = [p for p in outs if out_of_interest(p[2])]
    for d, w, nm in woi:
        A(f'    wire {w + " " if w else ""}w_{nm}; // observe {nm}')
    if not woi:
        A('    // (no *active/*valid/*done-looking output auto-detected; wire the one your property needs)')
    A('')
    A(f'    {name} u_dut (')
    conn = []
    for d, w, nm in ports:
        if d == 'input' and classify(nm) == 'clock':
            conn.append(f'        .{nm}(clk)')
        elif d == 'input' and classify(nm) == 'reset':
            conn.append(f'        .{nm}(rst_n)')
        elif d == 'input' and classify(nm) == 'enable':
            conn.append(f'        .{nm}({zero_lit(w)}) /* TODO ENABLE: drive per enabling protocol */')
        elif d == 'input':
            conn.append(f'        .{nm}({zero_lit(w)})')
        elif out_of_interest(nm):
            conn.append(f'        .{nm}(w_{nm})')
        else:
            conn.append(f'        .{nm}()')
    A(',\n'.join(conn))
    A('    );')
    A('')
    A('    // ============================ TODO 1: ENABLING PROTOCOL ============================')
    A('    // The DUT may only do anything after a configuration/enable sequence. Drive it here.')
    if enables:
        A('    // Flagged enable/config/mode inputs (verify which gate the logic under test):')
        for d, w, nm in enables:
            A(f'    //   .{nm}  -> currently tied {zero_lit(w)}; drive the real sequence if it gates your property')
    A('    //   Example (ext_backTelInterface): hold i_pcmReg_wr_en=1 so ext_if_cdc emits one o_sen')
    A('    //   pulse (~step 5) that latches r_sync_xfr_en_hs / r_btnop_sqsh_mode_hs. THEN fire the unit.')
    A('')
    A('    // ============================ TODO 2: INTENT PROPERTY =============================')
    A('    // Pick a template from property-library.md by the bug class (T4/T5/T6/FSM-safety).')
    A('    // Use immediate assert in a clocked block (yosys rejects assert property(@...)).')
    A('    always @(posedge clk) begin')
    A('        if (rst_n) begin')
    A('            assume (fire >= 8\'d6 && fire <= 8\'d12);   // scenario window (after config settles)')
    A('            // TODO: assert ( <intent> );   // e.g. T5: !armed || o_<active>')
    A('        end')
    A('    end')
    A('endmodule')
    A('`default_nettype wire')
    A('')
    A('// --- sby (save as <module>.sby) ---')
    A('// [options]\n//   mode bmc\n//   depth 20')
    A('// [engines]\n//   smtbmc z3')
    clk_note = 'single clock' if len(clocks) <= 1 else f'{len(clocks)} clocks COLLAPSED to clk (gives up CDC-timing tier)'
    A(f'// [script]\n//   read_verilog -sv -formal ftb.v {os.path.basename(path)} <deps...>')
    A(f'//   prep -top ftb')
    A(f'// NOTE: {clk_note}. clocks={[p[2] for p in clocks]} resets={[p[2] for p in resets]}')
    A(f'// NOTE: include transitive deps (instantiated modules) or the proof is unsound.')
    return '\n'.join(L)


if __name__ == '__main__':
    try:
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    except Exception:
        pass
    if len(sys.argv) < 2:
        print(__doc__); raise SystemExit(2)
    print(build(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None))
